In [8]:
import matplotlib.pyplot as plt
import numpy as np

In [9]:
nums_1d = np.ones((3), dtype=np.int8)
nums_1d

array([1, 1, 1], dtype=int8)

In [10]:
nums_2d = np.ones((3, 4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [11]:
nums_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [12]:
nums_3d = np.ones((2, 3, 4), dtype=np.int8)
nums_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [14]:
array_nums = np.array([3, 4])
array_nums

array([3, 4])

In [15]:
array_nums * 2

array([6, 8])

In [16]:
array_nums_more = np.array([10, 20])

In [17]:
array_nums * array_nums_more

array([30, 80])

In [18]:
array_nums + array_nums_more

array([13, 24])

In [19]:
array_nums - array_nums_more

array([ -7, -16])

In [20]:
array_nums / array_nums_more

array([0.3, 0.2])

In [21]:
np.ndarray((2, 4), np.int8)  # garbage data

array([[10,  0,  0,  0],
       [ 0,  0,  0,  0]], dtype=int8)

In [22]:
from numpy import random

rands = np.random.randn(2, 4) * 100  # random

In [26]:
rands.astype("int8")

array([[110, -59,  97, -90],
       [103, -65, -57, -75]], dtype=int8)

In [25]:
np.save("rands.npy", rands)

In [24]:
for i in rands:
    print(i)

[-146.65478024  -59.20894875   97.72059264  -90.56621166]
[103.63491161 -65.83934091 -57.00989463 -75.02209685]
